In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('personal_carbon_footprint_behavior.csv')
df

,user_id,day_type,transport_mode,distance_km,electricity_kwh,renewable_usage_pct,food_type,screen_time_hours,waste_generated_kg,eco_actions,carbon_footprint_kg,carbon_impact_level
0,1,Weekend,EV,1.55,6.12,0,Non-Veg,2.4,0.70,1,11.03,High
1,1,Weekend,Walk,10.04,4.50,0,Mixed,4.1,0.54,1,7.44,Medium
2,1,Weekday,Walk,15.27,2.81,0,Mixed,4.0,0.51,1,6.01,Medium
3,1,Weekend,Walk,0.50,10.16,0,Mixed,6.3,0.73,0,12.70,High
4,1,Weekend,Walk,3.60,5.02,50,Mixed,5.1,0.64,0,6.33,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
1395,200,Weekend,Bike,7.73,4.12,25,Veg,2.8,0.58,1,4.83,Low
1396,200,Weekend,Walk,5.20,4.72,75,Non-Veg,7.1,0.56,1,6.74,Medium
1397,200,Weekday,Bike,7.16,3.88,25,Non-Veg,3.2,0.72,2,7.95,Medium
1398,200,Weekday,Bus,10.91,3.84,75,Mixed,4.7,0.77,0,6.08,Medium
1399,200,Weekend,EV,7.69,5.34,50,Non-Veg,5.0,0.81,1,8.57,Medium

In [7]:
df[['user_id', 'carbon_footprint_kg']].groupby(['user_id']).mean()

         carbon_footprint_kg
user_id
1                   7.700000
2                   9.375714
3                   8.977143
4                   6.714286
5                   8.367143
...                      ...
196                 8.561429
197                 9.305714
198                 6.702857
199                 8.657143
200                 5.960000

[200 rows x 1 columns]

In [8]:
df[['day_type', 'carbon_footprint_kg']].groupby(['day_type']).mean()

          carbon_footprint_kg
day_type
Weekday              8.102497
Weekend              7.850412